package com.iei.dotshop.utils

object Constants {
    const val LANG = "lang"
    const val EN = "en"
    const val AR = "ar"
    const val IS_FIRST = "is_first"
    const val TOKEN = "token"
    const val FCM_TOKEN = "fcm_token"
    const val USER_ID = "user_id"
    const val USERNAME = "username"
    const val PHONE = "phone"
    const val COUNTRY_CODE = "country_code"
    const val USER_IMAGE = "user_image"
    const val EMAIL = "email"
    const val LAT = "lat"
    const val LNG = "lng"
    const val TITLE = "title"
    const val SELECTED_CITY = "selected_city"
    const val ADDRESS = "address"
    const val DISTANCE = "distance"
    const val DURATION = "duration"
    const val FIRST_NAME = "first_name"
    const val LAST_NAME = "last_name"
    const val LAT_LNG = "lat_lng"
    const val OPEN_NOTIFICATION = "open_notification"
    const val DRIVER_ID = "driver_id"
    const val DRIVER = "driver"
    const val TRIP_ID = "trip_id"
    const val TRIP = "trip"
    const val USER = "user"
    const val PAY = "pay"
    const val INVOICE = "invoice"
    const val PAYMENT_TEST_KEY = "pk_test_tgMfoDYEjJ1QwU6T9T3XTcPtrwHVK9pkJvTsSrao"
    const val PAYMENT_LIVE_KEY = "pk_live_C8VNJkAHpXcgrqpH8ninSuo3LEYMypsrQMxbYd6o"
    const val P_SUCCESS = 1
    const val P_FAILED = 0
    const val _DATA = "_data"
}